# Generated by Django 4.2.9 on 2024-01-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subcategory",
            name="category",
        ),
        migrations.AddField(
            model_name="subcategory",
            name="category",
            field=models.ManyToManyField(to="products.category"),
        ),
    ]
