# Generated by Django 4.2.9 on 2024-01-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_remove_subcategory_category_subcategory_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manufacturingcompany",
            name="sub_category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sub_category",
        ),
        migrations.AddField(
            model_name="manufacturingcompany",
            name="sub_category",
            field=models.ManyToManyField(to="products.subcategory"),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(to="products.category"),
        ),
        migrations.AddField(
            model_name="product",
            name="sub_category",
            field=models.ManyToManyField(to="products.subcategory"),
        ),
    ]
