# Generated by Django 4.2.9 on 2024-01-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_productimage_delete_productimages"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
